src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=ProductDimensionStock::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $productDimensionStock;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\GreaterThanOrEqual(1)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $orderRef;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductDimensionStock(): ?ProductDimensionStock
    {
        return $this->productDimensionStock;
    }

    public function setProductDimensionStock(?ProductDimensionStock $productDimensionStock): self
    {
        $this->productDimensionStock = $productDimensionStock;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): self
    {
        $this->orderRef = $orderRef;

        return $this;
    }
    /**
     * Tests if the given item given corresponds to the same order item.
     *
     * @param OrderItem $item
     *
     * @return bool
     */
    public function equals(OrderItem $item): bool
    {
        return $this->getProductDimensionStock()->getId() === $item->getProductDimensionStock()->getId();
    }
  /*  public function add($id, OrderItem $item)
    {
        if(!empty($item[$id])){
            $item[$id]++;
        }else{
            $item[$id]=1;
        }
    }*/

    /**
     * Calculates the item total.
     *
     * @return float|int
     */
    public function getTotal(): float
    {
        return $this->getProductDimensionStock()->getProduct()->getPrice() * $this->getQuantity();
    }

    /**
     * Calculates the item total.
     *
     * @return int
     */
    public function getTotalPoids(): int
    {
        return $this->getProductDimensionStock()->getPoids() * $this->getQuantity();
    }



}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('save', SubmitType::class,[
                'label'=>'sauvegarder',
            ])
            ->add('clear', SubmitType::class,[
                'label'=>'effacer',
            ]);

        $builder->addEventSubscriber(new RemoveCartItemListener());

        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Entity\Carrier;
use App\Entity\Order;
use App\Entity\Product;
use App\Form\CartType;
use App\Form\SelectDimensionType;
use App\Manager\CartManager;
use App\Entity\OrderItem;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{

    private $entityManager;

    /**
     * @param $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    /**
     * @Route("/cart", name="cart")
     */
    public function index(CartManager $cartManager, Request $request): Response
    {

        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {



            $cart->setUpdatedAt(new \DateTime());

            $cartManager->save($cart);

            return $this->redirectToRoute('cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,

            'form' => $form->createView(),
        ]);
    }

    #[Route('/cart/supprimer-un-product/{id}', name: 'cart_product_delete')]
    public function delete($id, CartManager $cartManager)
    {
        $orderItem=$this->entityManager->getRepository(OrderItem::class)->findOneById($id);
        $cart = $cartManager->getCurrentCart();

            $this->entityManager->remove($orderItem);
            $this->entityManager->flush();
            $cartManager->save($cart);

        return $this->redirectToRoute("cart");





    }

    #[Route('/cart/ajout-un-product/{id}', name: 'cart_product_add')]
    public function add($id, CartManager $cartManager)
    {
        $item=$this->entityManager->getRepository(OrderItem::class)->findOneById($id);
        $cart = $cartManager->getCurrentCart();

        $cart->moreItem($item);
        $this->entityManager->flush();
        $cartManager->save($cart);

        return $this->redirectToRoute("cart");





    }

    #[Route('/cart/retire-un-product/{id}', name: 'cart_product_less')]
    public function less($id, CartManager $cartManager)
    {
        $item=$this->entityManager->getRepository(OrderItem::class)->findOneById($id);
        $cart = $cartManager->getCurrentCart();

        $cart->lessItem($item);
        $this->entityManager->flush();
        $cartManager->save($cart);

        return $this->redirectToRoute("cart");





    }
    #[Route('/cart/supprimer', name: 'cart_delete')]
    public function remove( CartManager $cartManager)
    {
        $order=$this->entityManager->getRepository(Order::class)->findBy($this->getUser());
        $cart = $cartManager->getCurrentCart();

            $this->entityManager->remove($order);

            $this->entityManager->flush();
            $cartManager->remove($cart);
            $cartManager->save($cart);

        return $this->redirectToRoute("cart");


    }






}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h1>Mon panier</h1>
    <div class="container mt-4">

        {% if cart.items.count > 0 %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">

                    <div class="card">
                        <div class="card-header bg-dark text-white d-flex">
                            <h5 class="card-header bg-dark text-white">Articles</h5>
                            <div class="ml-auto">

                            </div>
                        </div>

                        <ul class="list-group list-group-flush">

                            {% for item in form.items %}

                                <li class="list-group-item d-flex">
                                    <div class="flex-fill mr-2">
                                        <img src="/uploads/{{ item.vars.data.productDimensionStock.product.illustration }}" alt="{{ item.vars.data.productDimensionStock.product.name }}" class="img-fluid" width="120px">
                                    </div>
                                    <div class="flex-fill mr-2">
                                        <h5 class="mt-0 mb-0">{{ item.vars.data.productDimensionStock.product.name }}</h5>
                                        <h4 class="mt-0 mb-0">{{ item.vars.data.productDimensionStock.dimension }}</h4>
                                        <small>{{ item.vars.data.productDimensionStock.product.description[:50] }}...</small>
                                        <h6>
                                            Quantité :
                                            <a href="{{ path('cart_product_less',{'id' : item.vars.data.id}) }}">
                                            <img src="{{ asset('assets/images/moins.png') }}" height="12px" alt="Supprimer mon produit">
                                            </a>
                                                x {{ item.vars.data.quantity }}
                                        <a href="{{ path('cart_product_add',{'id' : item.vars.data.id}) }}">
                                        <img src="{{ asset('assets/images/plus.png') }}" height="12px" alt="Ajouter mon produit">
                                        </a>
                                        </h6>

                                      
                                    </div>
                                    <div class="flex-fill mr-2 text-right">
                                        <b>{{ (item.vars.data.productDimensionStock.product.price / 100)|number_format(2,',', '.') }} €</b>
                                        <br />
                                        <a href="{{ path('cart_product_delete',{'id': item.vars.data.id}) }}">
                                            <img src="{{ asset('assets/images/trash.png') }}" height="20px" alt="supprimer">
                                        </a>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    {{ form_end(form, {'render_rest': false}) }}
                </div>
                <div class="col-md-4">
                    <div class="card mt-4 mt-md-0">
                        <h5 class="card-header bg-dark text-white">Résumé</h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between">
                                <div><b>Total</b></div>
                                <span><b>{{ (cart.total / 100)|number_format(2,',', '.')}} €</b></span>
                                <span><b>{{ cart.totalPoids }} g</b></span>
                            </li>
                        </ul>
                        <div class="card-body">
                            <a href="{{ path('command') }}" class="btn btn-warning w-100">Valider mon panier</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                Votre panier est vide. Aller à la <a href="{{ path('products') }}">Liste de produits</a>.
            </div>
        {% endif %}
    </div>
{% endblock %}